# web 访问端口号
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB
# 配置数据源信息
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 12345678
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-test-query: select 1
# mybatis 配置
mybatis:
  type-aliases-package: com.mhlevel.pojo
  mapper-locations: classpath:mapper/*.xml

# mybatis mapper 配置
mapper:
  mappers: com.mhlevel.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL
